Repository thewoowon/dentium.tech, pull requests merged in 2023-08, with the labels that each got.

#42 post: 서버 환경을 구축하기 위한 Kubernetes 도입기
  components/Banner.tsx
  package.json
  pages/index.tsx
  posts/20230716_kiwon_introduce_storybook.mdx
  posts/20230731_ryan_k8s.mdx
  yarn.lock
Labels: post

#44 post: 연산의 기술, 비트 매직
  pages/posts/[slug].tsx
  posts/20230402_george_interview.mdx
  posts/20230403_george_jeans.mdx
  posts/20230410_lucas_interview.mdx
  posts/20230411_ryan_interview.mdx
  posts/20230426_jm_interview.mdx
  posts/20230501_george_devrel.mdx
  posts/20230510_george_webpack.mdx
  posts/20230512_george_goods.mdx
  posts/20230520_lucas_graphql.mdx
  posts/20230603_george_jeans.mdx
  posts/20230604_george_login.mdx
  posts/20230606_ryan_graphql2.mdx
  posts/20230607_kw_interview.mdx
  posts/20230628_lucas_solid.mdx
  posts/20230716_kiwon_introduce_storybook.mdx
  posts/20230731_ryan_k8s.mdx
  posts/20230811_george_bit_magic.mdx
  styles/globals.css
Labels: documentation

#45 feat: renewal
  components/Accordion/Accordion.tsx
  components/Accordion/Cell/Cell.tsx
  components/Accordion/Cell/index.ts
  components/Accordion/index.ts
  components/Banner.tsx
  components/ElasticSwiperSlide.tsx
  components/Layout.tsx
  components/Navigation.tsx
  components/Notice.tsx
  components/Rolling.tsx
  next.config.js
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  states/index.ts
  styles/globals.css
  yarn.lock
Labels: enhancement

#46 feat: cube
  components/Banner.tsx
  components/Cube/Cube.tsx
  components/Cube/index.ts
  styles/globals.css
Labels: enhancement

#47 fix: urgent fix
  posts/20230811_george_bit_magic.mdx
Labels: enhancement

#48 feat: change photo, interview
  components/Rolling.tsx
  posts/20230425_lucas_mobx.mdx
  posts/20230430_ryan_architecture.mdx
  posts/20230510_george_webpack.mdx
  posts/20230520_lucas_graphql.mdx
  posts/20230604_george_login.mdx
  posts/20230606_ryan_graphql2.mdx
  posts/20230716_kiwon_introduce_storybook.mdx
  posts/20230811_george_bit_magic.mdx
Labels: enhancement
